version: "3.2"

services:
  pdi:
    image: pdi-front:0.0.0
    build:
      context: .
    # command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    # command: gunicorn app.main:app --reload -w 1 -k uvicorn.workers.UvicornWorker -b localhost:8100 --timeout 3600 --access-logfile -
    volumes:
      - ./:/usr/src/app/
    ports:
      - 80:8080
    networks:
      - pdi

networks:
  pdi:
    external: true